import { Seat } from "./seat";

export const SEATS: Seat[] = [
  {id:1, ws_id:1},
  {id:1, ws_id:1},
  {id:1, ws_id:1},
  {id:1, ws_id:1},
  {id:1, ws_id:2},
  {id:2, ws_id:2},
  {id:3, ws_id:2},
  {id:4, ws_id:2},
  {id:1, ws_id:3},
  {id:2, ws_id:3},
  {id:3, ws_id:3},
  {id:4, ws_id:3},
  {id:1, ws_id:4},
  {id:2, ws_id:4},
  {id:3, ws_id:4},
  {id:4, ws_id:4},
  {id:1, ws_id:5},
  {id:2, ws_id:5},
  {id:3, ws_id:5},
  {id:4, ws_id:5},
  {id:1, ws_id:6},
  {id:2, ws_id:6},
  {id:3, ws_id:6},
  {id:4, ws_id:6},
]